### ISSUE TITLE
[bug]: SQLite backend does not implement ListContracts

### ISSUE THREAD

**Issue by khaylebfortune** [sorotrail/SoroTrail#533]
## Description

`internal/store/sqlite.go` documents that `ListContracts` is not implemented for the SQLite backend. The `GET /contracts` endpoint therefore behaves differently depending on which database is configured, with nothing in the API surface signalling the difference.

## Requirements and context

This is scoped to be completable within a single Wave cycle and to pass CI on its own — it does not depend on any other open issue unless stated above.

- Repository: `sorotrail/SoroTrail`
- Contributor setup and test prerequisites: `CONTRIBUTING.md`
- Issue conventions: `.github/ISSUE_TEMPLATE/feature_request.yml`
- Primary files: `internal/store/sqlite.go`

## Suggested execution

1. Comment on this issue to be assigned before you start, so two people don't duplicate the work.
2. Fork the repository and create a branch:
   ```bash
   git checkout -b sqlite-backend-does-not-implement-listcontracts
   ```
3. Make the change described under **Implementation guidance**.
4. Run the commands under **Testing** and confirm they pass.
5. Commit using the format under **Example commit message**, push, and open a PR against `main`.

## What "done" looks like

- `GET /contracts` works on SQLite, or returns an explicit unsupported error.
- The behaviour is documented in the README next to the SQLite backend notes.
- A test pins whichever behaviour is chosen.

## Implementation guidance

- Touches: `internal/store/sqlite.go`.
- The Postgres implementation is the reference for pagination and `Scope` handling.
- Returning a typed error the API maps to 501 is preferable to returning an empty list.

## Testing

Run the checks CI runs, from the repository root:

```bash
go build ./...
go test ./internal/store/... -count=1
golangci-lint run
```

- Database-backed tests need Postgres: `make docker-up` then `make test-db`. Without `TEST_DATABASE_URL` those tests skip rather than fail.

## Example commit message

```
fix(store): sQLite backend does not implement ListContracts
```

## Guidelines

- **Complexity: Medium (150 points).** If the work turns out materially larger than this once you are in the code, say so on the issue rather than absorbing it — the tag should be corrected, not quietly outgrown.
- Comment to be assigned first; unassigned PRs may duplicate someone else's work.
- The PR description must link this issue (`Closes #<number>`) and state what you changed and how you verified it.
- Keep the PR to this issue's scope. Unrelated fixes you spot along the way are welcome as separate issues or PRs.
- CI must be green: build, `go vet` (plain and `-tags=integration`), the test suite, and `golangci-lint`.
- Match the surrounding code: this codebase favours full-sentence comments that explain *why*, not restatements of the code.
- If anything here is ambiguous, ask on the issue before building — a question costs less than a rewritten PR.

**Comment by Martinsbab** [comment]
@Martinsbab has applied to work on this issue as part of the **Stellar Wave Program**'s 9th wave.



> Hello I would like to work on this issue


ℹ️ **Repo Maintainers**: To accept this application, [review their application](https://www.drips.network/wave/maintainers/issues/26ee9842-d6ab-40fa-84a3-61849ed31417) or assign @Martinsbab to this issue.

**Comment by stephaniepez21-art** [comment]
@stephaniepez21-art has applied to work on this issue as part of the **Stellar Wave Program**'s 9th wave.



> Hi maintainer, I'd like to work on this. pls assign


ℹ️ **Repo Maintainers**: To accept this application, [review their application](https://www.drips.network/wave/maintainers/issues/26ee9842-d6ab-40fa-84a3-61849ed31417) or assign @stephaniepez21-art to this issue.

**Comment by meem08** [comment]
@meem08 has applied to work on this issue as part of the **Stellar Wave Program**'s 9th wave.



> I will like to work on this issue 


ℹ️ **Repo Maintainers**: To accept this application, [review their application](https://www.drips.network/wave/maintainers/issues/26ee9842-d6ab-40fa-84a3-61849ed31417) or assign @meem08 to this issue.

**Comment by AYOMI-cmd** [comment]
@AYOMI-cmd has applied to work on this issue as part of the **Stellar Wave Program**'s 9th wave.



> Hello Maintainer, I can fix this.


ℹ️ **Repo Maintainers**: To accept this application, [review their application](https://www.drips.network/wave/maintainers/issues/26ee9842-d6ab-40fa-84a3-61849ed31417) or assign @AYOMI-cmd to this issue.
