### ISSUE TITLE
[bug]: SQLite backend does not implement per-contract cursors

### ISSUE THREAD

**Issue by khaylebfortune** [sorotrail/SoroTrail#534]
## Description

`internal/store/sqlite.go` documents that per-contract cursors are not implemented for SQLite. A deployment that sets `WATCHED_CONTRACTS` against SQLite therefore silently loses the per-contract resume model the README describes.

## Requirements and context

This is scoped to be completable within a single Wave cycle and to pass CI on its own — it does not depend on any other open issue unless stated above.

- Repository: `sorotrail/SoroTrail`
- Contributor setup and test prerequisites: `CONTRIBUTING.md`
- Issue conventions: `.github/ISSUE_TEMPLATE/feature_request.yml`
- Primary files: `internal/store/sqlite.go`, `internal/store/migrations/sqlite/`

## Suggested execution

1. Comment on this issue to be assigned before you start, so two people don't duplicate the work.
2. Fork the repository and create a branch:
   ```bash
   git checkout -b sqlite-backend-does-not-implement-per-contract
   ```
3. Make the change described under **Implementation guidance**.
4. Run the commands under **Testing** and confirm they pass.
5. Commit using the format under **Example commit message**, push, and open a PR against `main`.

## What "done" looks like

- Per-contract cursors work on SQLite, or the process refuses to start in watched mode against SQLite.
- The limitation is documented.
- A test pins the chosen behaviour.

## Implementation guidance

- Touches: `internal/store/sqlite.go`, `internal/store/migrations/sqlite/`.
- A schema change needs a new SQLite migration; the series is applied by `migrateSQLite`, not golang-migrate.

## Testing

Run the checks CI runs, from the repository root:

```bash
go build ./...
go test ./internal/store/... ./internal/store/migrations/sqlite//... -count=1
golangci-lint run
```

- `go test ./internal/store/ -run TestMigrate -count=1` validates migration loading and version uniqueness without needing a database.
- Database-backed tests need Postgres: `make docker-up` then `make test-db`. Without `TEST_DATABASE_URL` those tests skip rather than fail.

## Example commit message

```
fix(store): sQLite backend does not implement per-contract cursors
```

## Guidelines

- **Complexity: Medium (150 points).** If the work turns out materially larger than this once you are in the code, say so on the issue rather than absorbing it — the tag should be corrected, not quietly outgrown.
- Comment to be assigned first; unassigned PRs may duplicate someone else's work.
- The PR description must link this issue (`Closes #<number>`) and state what you changed and how you verified it.
- Keep the PR to this issue's scope. Unrelated fixes you spot along the way are welcome as separate issues or PRs.
- CI must be green: build, `go vet` (plain and `-tags=integration`), the test suite, and `golangci-lint`.
- Match the surrounding code: this codebase favours full-sentence comments that explain *why*, not restatements of the code.
- If anything here is ambiguous, ask on the issue before building — a question costs less than a rewritten PR.

**Comment by AdEmOnD07** [comment]
@AdEmOnD07 has applied to work on this issue as part of the **Stellar Wave Program**'s 9th wave.



> I would like to work on this issue ASAP 
> I will deliver best and fast 


ℹ️ **Repo Maintainers**: To accept this application, [review their application](https://www.drips.network/wave/maintainers/issues/ce9c9c77-6463-4e58-abf9-951016ad12f5) or assign @AdEmOnD07 to this issue.

**Comment by laxjovial** [comment]
@laxjovial has applied to work on this issue as part of the **Stellar Wave Program**'s 9th wave.



> i can fix this, kindly assign


ℹ️ **Repo Maintainers**: To accept this application, [review their application](https://www.drips.network/wave/maintainers/issues/ce9c9c77-6463-4e58-abf9-951016ad12f5) or assign @laxjovial to this issue.
